# Generated by Django 5.0 on 2024-01-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='question',
            new_name='solution_question',
        ),
    ]
