# Generated by Django 5.0 on 2024-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_question_question_topics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_title",
            field=models.CharField(max_length=1000),
        ),
    ]
