# Generated by Django 5.0 on 2024-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_question_question_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_status",
            field=models.CharField(
                choices=[
                    ("Weak", "Weak"),
                    ("Average", "Average"),
                    ("Strong", "Strong"),
                    ("Very Strong", "Very Strong"),
                    ("Master", "Master"),
                    ("Solve Later", "Solve Later"),
                    ("Revisit", "Revisit"),
                    ("Revised", "Revised"),
                ],
                max_length=100,
            ),
        ),
    ]
