# Generated by Django 5.0 on 2024-06-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Contest Question', 'Contest Question'), ('General Practice', 'General Practice'), ('Daily Challenge', 'Daily Challenge'), ('Interview Question', 'Interview Question'), ('Important Algorithm', 'Important Algorithm')], max_length=100),
        ),
    ]
